{ **************************************************** }
{     DeLaFits - Library FITS for Delphi & Lazarus     }
{                                                      }
{     Suppress a wrong compiler hints and warnings     }
{                                                      }
{          Copyright(c) 2013-2021, felleroff           }
{              delafits.library@gmail.com              }
{        https://github.com/felleroff/delafits         }
{ **************************************************** }

{$IFDEF FPC}
  {$I DeLaFitsSuppress.fpc}
{$ENDIF}

{$IFDEF DCC}
  {$I DeLaFitsSuppress.dcc}
{$ENDIF}
